# SwiftLint configuration
# https://github.com/realm/SwiftLint#configuration

disabled_rules:
   - line_length         # Ignore line length rules
   - trailing_whitespace # Allow lines to only contain a TAB, since Xcode does this by default on newlines
   - todo                # Allow TODO comments
   - identifier_name     # Allow vars that use non-alphanumberic characters

force_cast: warning
force_try: warning

excluded:
  - Pods
